package vio.errors

enum class ErrorCode {
    BOOK_NOT_FOUND,
    UNSUPPORTED_LANGUAGE,
    UPLOAD_LIMIT_EXCEEDED,
    INVALID_FILE,
    UNSUPPORTED_FILE_TYPE,
    PHRASE_NOT_FOUND,
    USER_NOT_FOUND,
    USER_EXISTS_ALREADY,
    INVALID_TOKEN
}